### ISSUE TITLE
Warning: curl_setopt(): You must pass either an object or an array with the CURLOPT_HTTPHEADER argument

### ISSUE THREAD

**Issue by quantizer** [dmamontov/amo-restapi#2]
Warning: curl_setopt(): You must pass either an object or an array with the CURLOPT_HTTPHEADER argument

in vendor/dmamontov/amo-restapi/AmoRestApi.php at line 631:

```
    631    curl_setopt($this->curl, CURLOPT_HTTPHEADER, false);
    632    if (is_null($headers) === false) {
    633        curl_setopt($this->curl, CURLOPT_HTTPHEADER, $headers);
```

**Comment by quantizer** [comment]
If pass empty array `curl_setopt($this->curl, CURLOPT_HTTPHEADER, array());` you will have exceptions without message. And `$result = null`

```
        if ($statusCode >= 400) {
            var_dump($result);
            throw new Exception($result['message'], $statusCode);
        }
```

**Comment by dmamontov** [comment]
Fixed. Should no longer appear.
